### ISSUE TITLE
we should probably get even more specific here (in later iterations)

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-fossati-cose-profile#3]
we should probably get even more specific here (in later iterations)

_Originally posted by @henkbirkholz in https://github.com/thomas-fossati/draft-fossati-cose-profile/pull/1#discussion_r1042443147_

**Comment by henkbirkholz** [comment]
One possible elaboration: we should retain the "COSE tag" from RF 9052 and prepend it with a profile tag

**Comment by thomas-fossati** [comment]
the clarification is already in the editor's copy
