### ISSUE TITLE
Define test vectors for each value type of the COSE profile header parameter

### ISSUE THREAD

**Issue by letmaik** [thomas-fossati/draft-fossati-cose-profile#7]
- Test vectors in JSON
- a simple reference encoder/decoder using an off-the-shelve CBOR library
- a test script that runs all test vectors against the reference implementation

Proposed JSON format:

```json
{
  "title": "OID profile",
  "fail": false,
  "cbor": "...hex...",
  "type": "oid",
  "value": "1.2.3.4"
}
```

The above could be used to test both encoder and decoder. For error cases I would focus on decoding only:

```json
{
  "title": "Invalid URI profile (tagged)",
  "fail": true,
  "cbor": "...hex.."
}
```

**Comment by thomas-fossati** [comment]
This is a beautiful idea.  But it should be tracked in the [gluecose org](https://github.com/gluecose/test-vectors/issues/13).
